import { NextRequest, NextResponse } from 'next/server'
import { Types } from 'mongoose'
import { auth } from '@/lib/auth'
import { normalizeExcoRole } from '@/lib/exco-constants'
import { connectDB } from '@/lib/db'
import CampusLocation from '@/models/campus-location'
import { validateCampusLocationInput } from '@/lib/campus-location'
async function authorized(headers: Headers) { const session = await auth.api.getSession({ headers }); return session?.user && (session.user.role === 'admin' || Boolean(normalizeExcoRole((session.user as { excoRole?: string }).excoRole))) }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { if (!await authorized(request.headers)) return NextResponse.json({ error: 'Forbidden.' }, { status: 403 }); const { id } = await params; if (!Types.ObjectId.isValid(id)) return NextResponse.json({ error: 'Invalid location.' }, { status: 400 }); await connectDB(); const current = await CampusLocation.findById(id); if (!current) return NextResponse.json({ error: 'Location not found.' }, { status: 404 }); const body = await request.json(); if (typeof body.active === 'boolean' && Object.keys(body).length === 1) { current.active = body.active; await current.save(); return NextResponse.json({ location: current }) } const input = validateCampusLocationInput(body); const parentId = body.parentLocationId || null; if (parentId === id) return NextResponse.json({ error: 'A location cannot be its own parent.' }, { status: 400 }); if (parentId && (!Types.ObjectId.isValid(parentId) || !await CampusLocation.exists({ _id: parentId }))) return NextResponse.json({ error: 'Parent location was not found.' }, { status: 400 }); if (parentId) { let cursor: string | null = parentId; while (cursor) { if (cursor === id) return NextResponse.json({ error: 'A location cannot be moved under its descendant.' }, { status: 400 }); const parent = await CampusLocation.findById(cursor).select('parentLocationId').lean(); cursor = parent?.parentLocationId ? String(parent.parentLocationId) : null } } Object.assign(current, input, { parentLocationId: parentId }); await current.save(); return NextResponse.json({ location: current }) } catch (error) { if (error instanceof Error) { if ((error as Error & { code?: number }).code === 11000) return NextResponse.json({ error: 'A location with this name already exists under that parent.' }, { status: 409 }); return NextResponse.json({ error: error.message }, { status: 400 }) } return NextResponse.json({ error: 'Failed to update location.' }, { status: 500 }) } }
export async function DELETE(request: NextRequest, context: { params: Promise<{ id: string }> }) { return PATCH(new NextRequest(request.url, { method: 'PATCH', headers: request.headers, body: JSON.stringify({ active: false }) }), context) }
