import { NextRequest, NextResponse } from 'next/server'
import { Types } from 'mongoose'
import { auth } from '@/lib/auth'
import { normalizeExcoRole } from '@/lib/exco-constants'
import { connectDB } from '@/lib/db'
import CampusLocation from '@/models/campus-location'
import { validateCampusLocationInput } from '@/lib/campus-location'

async function authorized(headers: Headers) { const session = await auth.api.getSession({ headers }); return session?.user && (session.user.role === 'admin' || Boolean(normalizeExcoRole((session.user as { excoRole?: string }).excoRole))) ? session.user : null }
export async function GET(request: NextRequest) { try { if (!await authorized(request.headers)) return NextResponse.json({ error: 'Forbidden.' }, { status: 403 }); await connectDB(); const q = request.nextUrl.searchParams; const filter: Record<string, unknown> = {}; const search = q.get('search')?.trim(); if (search) filter.$or = [{ name: { $regex: search, $options: 'i' } }, { shortName: { $regex: search, $options: 'i' } }]; if (q.get('type')) filter.type = q.get('type'); if (q.get('active') === 'true' || q.get('active') === 'false') filter.active = q.get('active') === 'true'; if (q.get('parentLocationId')) { if (!Types.ObjectId.isValid(q.get('parentLocationId')!)) return NextResponse.json({ error: 'Invalid parent location.' }, { status: 400 }); filter.parentLocationId = q.get('parentLocationId') } const locations = await CampusLocation.find(filter).sort({ parentLocationId: 1, name: 1 }).lean(); const counts = await CampusLocation.aggregate([{ $match: { parentLocationId: { $ne: null } } }, { $group: { _id: '$parentLocationId', count: { $sum: 1 } } }]); const childCounts = Object.fromEntries(counts.map(item => [String(item._id), item.count])); return NextResponse.json({ locations: locations.map(location => ({ ...location, childCount: childCounts[String(location._id)] || 0 })) }) } catch (error) { console.error('[GET /api/admin/locations]', error); return NextResponse.json({ error: 'Failed to load locations.' }, { status: 500 }) } }
export async function POST(request: NextRequest) { try { const user = await authorized(request.headers); if (!user) return NextResponse.json({ error: 'Forbidden.' }, { status: 403 }); const body = await request.json(); const input = validateCampusLocationInput(body); const parentId = body.parentLocationId || null; await connectDB(); if (parentId && (!Types.ObjectId.isValid(parentId) || !await CampusLocation.exists({ _id: parentId }))) return NextResponse.json({ error: 'Parent location was not found.' }, { status: 400 }); const location = await CampusLocation.create({ ...input, parentLocationId: parentId, createdBy: user.id, source: 'admin_manual', observationCount: 1 }); return NextResponse.json({ location }, { status: 201 }) } catch (error) { if (error instanceof Error) { if ((error as Error & { code?: number }).code === 11000) return NextResponse.json({ error: 'A location with this name already exists under that parent.' }, { status: 409 }); return NextResponse.json({ error: error.message }, { status: 400 }) } return NextResponse.json({ error: 'Failed to create location.' }, { status: 500 }) } }
