'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { toast } from 'sonner'
import { captureDeliveryPosition } from '@/lib/delivery-coordinates'
import { CAMPUS_LOCATION_TYPES, type CampusLocationType } from '@/lib/campus-location'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { MapPin, Navigation, Plus, RotateCcw, Search, X } from 'lucide-react'

type Coordinates = { latitude: number; longitude: number; accuracy: number; capturedAt: string }
type Location = { _id: string; name: string; type: CampusLocationType; parentLocationId?: string | null; active: boolean; coordinates: Coordinates; childCount: number; createdAt: string; updatedAt: string }
const labels: Record<CampusLocationType, string> = { building: 'Building', hostel: 'Hostel', lecture_theatre: 'Lecture theatre', room: 'Room', entrance: 'Entrance', shop: 'Shop', cafeteria: 'Cafeteria', pickup_point: 'Pickup point', landmark: 'Landmark', other: 'Other' }
const empty = { name: '', type: 'building' as CampusLocationType, parentLocationId: '' }

export default function AdminLocationsPage() {
  const [locations, setLocations] = useState<Location[]>([]), [form, setForm] = useState(empty), [parentQuery, setParentQuery] = useState(''), [coordinates, setCoordinates] = useState<Coordinates | null>(null), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [capturing, setCapturing] = useState(false), [editing, setEditing] = useState<Location | null>(null), [search, setSearch] = useState(''), [type, setType] = useState('all'), [active, setActive] = useState('active')
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch('/api/admin/locations'); const data = await response.json(); if (!response.ok) throw new Error(data.error); setLocations(data.locations) } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load locations.') } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  const parents = useMemo(() => locations.filter(location => !location.parentLocationId && location._id !== editing?._id), [locations, editing])
  const filtered = useMemo(() => locations.filter(location => { const text = location.name.toLowerCase(); return (!search || text.includes(search.toLowerCase())) && (type === 'all' || location.type === type) && (active === 'all' || location.active === (active === 'active')) }), [locations, search, type, active])
  const parentName = (id?: string | null) => locations.find(location => location._id === id)?.name
  const capture = async () => { setCapturing(true); try { setCoordinates(await captureDeliveryPosition()) } catch (error) { toast.error(error instanceof Error ? `We couldn't get your current location. ${error.message}` : "We couldn't get your current location.") } finally { setCapturing(false) } }
  const reset = () => { setForm(empty); setParentQuery(''); setCoordinates(null); setEditing(null) }
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!coordinates) return toast.error('Confirm your current location before saving.'); setSaving(true); try { const response = await fetch(editing ? `/api/admin/locations/${editing._id}` : '/api/admin/locations', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, parentLocationId: form.parentLocationId || null, coordinates }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success(editing ? 'Location updated.' : 'Location saved.'); reset(); await load() } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save location.') } finally { setSaving(false) } }
  const edit = (location: Location) => { setEditing(location); setForm({ name: location.name, type: location.type, parentLocationId: location.parentLocationId || '' }); setParentQuery(parentName(location.parentLocationId) || ''); setCoordinates(location.coordinates); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const deactivate = async (location: Location) => { try { const response = await fetch(`/api/admin/locations/${location._id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ active: !location.active }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success(location.active ? 'Location deactivated.' : 'Location reactivated.'); await load() } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to update location.') } }
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:py-10"><header className="mb-6"><p className="text-sm font-semibold text-violet-700">Campus operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Campus Locations</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Build SwiftDU&apos;s campus map by saving verified locations and sublocations.</p></header>
    <form onSubmit={save} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between gap-4"><div><h2 className="font-bold text-slate-950">{editing ? 'Edit location' : 'Add location'}</h2><p className="mt-1 text-sm text-slate-500">Capture GPS while standing at the location. Indoor room readings may be approximate.</p></div>{editing && <Button type="button" variant="ghost" onClick={reset}><X className="mr-2 h-4 w-4" />Cancel</Button>}</div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Parent location<Input list="campus-parent-locations" value={parentQuery} onChange={event => { const value = event.target.value; const parent = parents.find(item => item.name === value); setParentQuery(value); setForm({ ...form, parentLocationId: parent?._id || '' }) }} placeholder="Type or select a parent location" className="mt-1" /><datalist id="campus-parent-locations"><option value="" label="No parent location" />{parents.map(parent => <option key={parent._id} value={parent.name} />)}</datalist></label><label className="text-sm font-semibold text-slate-700">Location name *<Input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Postgraduate Lecture Theatre" className="mt-1" /></label><label className="text-sm font-semibold text-slate-700">Location type *<select required value={form.type} onChange={event => setForm({ ...form, type: event.target.value as CampusLocationType })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{CAMPUS_LOCATION_TYPES.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></label></div>{form.parentLocationId && <p className="mt-4 rounded-xl bg-violet-50 px-3 py-2 text-sm font-medium text-violet-800">{parentName(form.parentLocationId)} <span aria-hidden>→</span> {form.name || 'New sublocation'}</p>}
      <div className="mt-5 rounded-2xl border border-violet-100 bg-violet-50/50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">GPS capture</p><p className="mt-1 text-sm text-slate-600">Your browser will request precise location permission.</p></div><Button type="button" onClick={capture} disabled={capturing} className="bg-violet-600 hover:bg-violet-700">{capturing ? 'Getting your location…' : coordinates ? <><RotateCcw className="mr-2 h-4 w-4" />Retake Location</> : <><Navigation className="mr-2 h-4 w-4" />Confirm Current Location</>}</Button></div>{coordinates && <div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Metric label="Latitude" value={coordinates.latitude.toFixed(6)} /><Metric label="Longitude" value={coordinates.longitude.toFixed(6)} /><Metric label="Accuracy" value={`± ${Math.round(coordinates.accuracy)} m`} /><Metric label="Captured" value="Just now" /></div>}{coordinates && coordinates.accuracy > 25 && <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-800">GPS accuracy is currently ±{Math.round(coordinates.accuracy)} m. For better mapping, move outdoors or closer to a window and capture again.</p>}</div><div className="mt-5 flex flex-wrap gap-3"><Button type="submit" disabled={saving || !coordinates} className="bg-violet-600 hover:bg-violet-700"><Plus className="mr-2 h-4 w-4" />{saving ? 'Saving…' : editing ? 'Save changes' : 'Save Location'}</Button>{!coordinates && <span className="self-center text-xs text-slate-500">GPS capture is required to save.</span>}</div></form>
    <section className="mt-8"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold text-slate-950">Mapped locations</h2><p className="text-sm text-slate-500">Manage campus landmarks and their sublocations.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><div className="relative col-span-2 sm:w-60"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={event => setSearch(event.target.value)} className="pl-9" placeholder="Search name or code" /></div><select value={type} onChange={event => setType(event.target.value)} className="min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All types</option>{CAMPUS_LOCATION_TYPES.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select><select value={active} onChange={event => setActive(event.target.value)} className="min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All status</option></select></div></div>{loading ? <p className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500">Loading locations…</p> : filtered.length === 0 ? <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><MapPin className="mx-auto h-10 w-10 text-violet-300" /><p className="mt-3 font-semibold text-slate-800">No mapped locations yet</p><p className="mt-1 text-sm text-slate-500">Walk to a location, capture GPS, and save the first campus point.</p></div> : <div className="space-y-3">{filtered.filter(location => !location.parentLocationId).map(location => <LocationCard key={location._id} location={location} childLocations={filtered.filter(child => child.parentLocationId === location._id)} onEdit={edit} onDeactivate={deactivate} />)}{filtered.filter(location => location.parentLocationId && !locations.some(parent => parent._id === location.parentLocationId && filtered.includes(parent))).map(location => <LocationCard key={location._id} location={location} childLocations={[]} parentName={parentName(location.parentLocationId)} onEdit={edit} onDeactivate={deactivate} />)}</div>}</section></div>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate font-semibold text-slate-900">{value}</p></div> }
function LocationCard({ location, childLocations, parentName, onEdit, onDeactivate }: { location: Location; childLocations: Location[]; parentName?: string; onEdit: (location: Location) => void; onDeactivate: (location: Location) => void }) { return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-950">{location.name}</h3>{!location.active && <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-500">Inactive</span>}</div><p className="mt-1 text-sm text-slate-500">{parentName ? <>{parentName} <span aria-hidden>→</span> {location.name}</> : labels[location.type]}{!parentName && location.childCount > 0 ? ` · ${location.childCount} sublocation${location.childCount === 1 ? '' : 's'}` : ''}</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={() => onEdit(location)}>Edit / Recapture GPS</Button><Button type="button" variant="outline" size="sm" onClick={() => onDeactivate(location)} className={location.active ? 'text-rose-700' : 'text-emerald-700'}>{location.active ? 'Deactivate' : 'Reactivate'}</Button></div></div>{childLocations.length > 0 && <div className="mt-4 grid gap-2 border-t border-slate-100 pt-3 sm:grid-cols-2">{childLocations.map(child => <button key={child._id} type="button" onClick={() => onEdit(child)} className="rounded-xl bg-slate-50 px-3 py-2 text-left text-sm hover:bg-violet-50"><span className="font-semibold text-slate-800">{child.name}</span><span className="ml-2 text-xs text-slate-500">{labels[child.type]}</span></button>)}</div>}</article> }
